/*
 * Copyright 2010-2016 JetBrains s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.jetbrains.kotlin.codegen;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.TestsPackage}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler/testData/codegen/fullBytecodeText")
@TestDataPath("$PROJECT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
public class FullBytecodeTextTestGenerated extends AbstractFullBytecodeTextTest {
    public void testAllFilesPresentInFullBytecodeText() throws Exception {
        KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/codegen/fullBytecodeText"), Pattern.compile("^(.+)\\.kt$"), true);
    }

    @TestMetadata("compiler/testData/codegen/fullBytecodeText/optimizedPostIncrement")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class OptimizedPostIncrement extends AbstractFullBytecodeTextTest {
        public void testAllFilesPresentInOptimizedPostIncrement() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/codegen/fullBytecodeText/optimizedPostIncrement"), Pattern.compile("^(.+)\\.kt$"), true);
        }

        @TestMetadata("byteArray.kt")
        public void testByteArray() throws Exception {
            String fileName = KotlinTestUtils.navigationMetadata("compiler/testData/codegen/fullBytecodeText/optimizedPostIncrement/byteArray.kt");
            doTest(fileName);
        }

        @TestMetadata("byteGlobalField.kt")
        public void testByteGlobalField() throws Exception {
            String fileName = KotlinTestUtils.navigationMetadata("compiler/testData/codegen/fullBytecodeText/optimizedPostIncrement/byteGlobalField.kt");
            doTest(fileName);
        }

        @TestMetadata("byteLocalVar.kt")
        public void testByteLocalVar() throws Exception {
            String fileName = KotlinTestUtils.navigationMetadata("compiler/testData/codegen/fullBytecodeText/optimizedPostIncrement/byteLocalVar.kt");
            doTest(fileName);
        }

        @TestMetadata("bytePropInClass.kt")
        public void testBytePropInClass() throws Exception {
            String fileName = KotlinTestUtils.navigationMetadata("compiler/testData/codegen/fullBytecodeText/optimizedPostIncrement/bytePropInClass.kt");
            doTest(fileName);
        }

        @TestMetadata("longArray.kt")
        public void testLongArray() throws Exception {
            String fileName = KotlinTestUtils.navigationMetadata("compiler/testData/codegen/fullBytecodeText/optimizedPostIncrement/longArray.kt");
            doTest(fileName);
        }

        @TestMetadata("longGlobalField.kt")
        public void testLongGlobalField() throws Exception {
            String fileName = KotlinTestUtils.navigationMetadata("compiler/testData/codegen/fullBytecodeText/optimizedPostIncrement/longGlobalField.kt");
            doTest(fileName);
        }

        @TestMetadata("longLocalVar.kt")
        public void testLongLocalVar() throws Exception {
            String fileName = KotlinTestUtils.navigationMetadata("compiler/testData/codegen/fullBytecodeText/optimizedPostIncrement/longLocalVar.kt");
            doTest(fileName);
        }

        @TestMetadata("longPropInClass.kt")
        public void testLongPropInClass() throws Exception {
            String fileName = KotlinTestUtils.navigationMetadata("compiler/testData/codegen/fullBytecodeText/optimizedPostIncrement/longPropInClass.kt");
            doTest(fileName);
        }
    }
}
